# Generated by Django 2.0.6 on 2018-06-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(null=True, upload_to='gallery')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=254)),
                ('duration', models.IntegerField(null=True)),
                ('price', models.CharField(default='19.00', max_length=5)),
                ('category', models.CharField(default='Default', max_length=64)),
            ],
        ),
    ]
